config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :links, only: [:new, :create, :edit], shallow: true
  end

  resources :friends, :controller => 'friendships', :except => [:show, :edit] do
    get "requests", :on => :collection
    get "invites", :on => :collection
  end
  post "friends", to: "friendships#create", as: "friend_create"
  delete "/friends/", to: "friendships#delete", as: "friend_delete"
  delete "/friends/", to: "friendships#destroy", as: "friend_destroy"  
  patch "links/pre_send/:sender_id/:link_id", to: "links#pre_send", as: "pre_send"
  patch "links/send/:sender_id/:link_id/username", to: "links#send_link", as: "send"

  root 'users#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
	validates :url, presence: true
	validates :points, presence: true
	validates :user_id, presence: true
	validates :title, presence: true
	serialize :receivers
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :name, presence: true
  validates :email, presence: true
  serialize :received
  include Amistad::FriendModel
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?	
  protect_from_forgery with: :exception
  protected
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name	
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @user = current_user
    @friends = current_user.friends
  end

  def new
    @user = current_user
    @users = User.all
    @invitee = User.new

  end

  def create
    @invitee = User.find_by_name params[:user][:name]
    if @invitee
      if current_user.invite @invitee
        redirect_to root_path, :notice => "Successfully invited friend!"
      else
        redirect_to root_path, :notice => "Sorry! You can't invite that user!"
      end
    else
      redirect_to new_friend_path, :notice => "Sorry! You can't invite that user!"
    end
  end

  def update
    @inviter = User.find params[:id]
    if @inviter
      if current_user.approve @inviter
        redirect_to root_path, :notice => "Successfully confirmed friend!"
      else
        redirect_to new_friend_path, :notice => "Sorry! Could not confirm friend!"
      end
    end
  end

  def requests
    @pending_requests = current_user.pending_invited_by
  end

  def invites
    @pending_invites = current_user.pending_invited
  end

  def delete
    @user = User.find params[:user_id]
    @deleter = current_user
    @deletee = User.new
  end

  def destroy
    @deletee = User.find_by_name params[:user][:name]
    if @deletee
      if current_user.remove_friendship @deletee
        redirect_to friends_path, :notice => "Successfully removed friend!"
      else
        redirect_to friends_path, :notice => "Sorry, couldn't remove friend!"
      end
    end
  end


end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def new
    @user = User.find params[:user_id]
    @link = Link.new
  end

  def create
    @user = User.find params[:user_id]
    @link = Link.create(link_params)
    @link.user_id = params[:user_id]
    @link.points = 0
    if @link.save!
      redirect_to root_path
    else
      render "new"
    end
  end

  def pre_send
    @link = Link.find(params[:link_id])
    @sender = User.find(params[:sender_id])
    @username = params[:username]
  end 

  def send_link
    @users = User.all
    @link = Link.find(params[:link_id])
    @sender = User.find(params[:sender_id])
    @users.each do |u|
      if u.name == params[:username]
        @user = u
        break
      end
    end  
    if not @user
      redirect_to root_path
    else
      #@user = User.find(params[:sender_id])
      if not @link.receivers
        @link.receivers =[]
      end
      if not @user.received
        @user.received = []
      end
      if not @user.received.include?(@link.id)
        @link.receivers.push([@user.id, @sender.id])
        @user.received.push(@link.id)
        @link.points = @link.points + 10
      end
      if @link.save! and @user.save!
        redirect_to root_path
      else
        render "new"
      end
    end
  end

  def edit
    @link = Link.find params[:id]
  end

#  def update
 #   @link = Link.find params[:id]
  #  if @link.update link_params
   #   redirect_to @link.user
    #end
  #end

  private

  def link_params
    params.require(:link).permit(:url, :title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
  	@user = User.find params[:id]
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friendships/delete.html.erb
<h1>Delete a friend, <%= @user.name %>!</h1>

<%= simple_form_for @deletee, :url => friend_destroy_path, :class => "btn btn-info" do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, "Remove Friend" %>
<% end %>

app/views/friendships/index.html.erb
<% if @friends.count == 0 %>
	<h2> You currently have no friends</h2>
	<%= button_to "Add a Friend!", new_friend_path(user_id: current_user.id), :class => "btn btn-info", :method => :get %>
<% else %>
	<h2>You have <%= @friends.count %> friend(s).</h2>
	<% @friends.each do |t| %>
		<%= t.name %>
	<% end %>
	<%= button_to "Add more Friends!", new_friend_path(user_id: current_user.id), :class => "btn btn-info", :method => :get %>
<% end %>

<% if @user.pending_invited_by.count == 0 %>
	<h3> You currently have no friend requests</h2>
<% else %>
	<h3> You have <%= @user.pending_invited_by.count %> friend request(s) </h3>
	<% @user.pending_invited_by.each do |t| %>
		<%= t.name %>
		<%= button_to "Accept!", friend_path(id: t.id, user_id: current_user.id), :class => "btn btn-info", :method => :patch %>
	<% end %>
<%end %>

<% if @user.pending_invited.count == 0 %>
	<h3> You currently have no pending friend approval</h2>
<% else %>
	<h3> You have sent out<%= @user.pending_invited.count %> friend request(s) </h3>
	<% @user.pending_invited_by.each do |t| %>
		<%= t.name %>
	<% end %>
<%end %>

<h2> Dont Like Someone?</h2>
	<%= button_to "Remove a Friend!", friend_delete_path(user_id: current_user.id), :class => "btn btn-info", :method => :delete %>

app/views/friendships/new.html.erb
<h1>Add a new friend, <%= @user.name %>!</h1>

<%= simple_form_for @invitee, :url => friend_create_path do |f| %>
  <%= f.input :name %>
  <%= f.button :submit, "Add" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Linq" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body class = "img"> 

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Home</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if current_user %> 
              <li><%= link_to current_user.name, user_path(current_user) %></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/links/edit.html.slim
h1 Changing a Link is no Problemo

= simple_form_for @link do |f|
  = f.input :url
  = f.button :submit

app/views/links/new.html.erb
<div class = "row fluid">
	<div class = "span6 well">
<h3>A New Link for <%= @user.name %></h3>

<%= simple_form_for @link, :url => user_links_path do |f| %>
  <%= f.input :title %>
  <%= f.input :url %>
  <%= f.button :submit, "Create" %>
<% end %>


</div>
</div>

app/views/links/pre_send.html.erb
<h1>Send link</h1>

<%= simple_form_for @link, :url => send_path(link_id: @link.id, sender_id: current_user.id, username: @username) do |f| %>
  <%= text_field_tag :username %>
  <%= submit_tag 'Send' %>
<% end %>

<!--<%= form_tag send_path, method: :patch do %>
  <%= text_field_tag :user_name %>
  <%= submit_tag 'Send' %>
<% end %>-->

<!--<%= text_field_tag(:username) %>
<%= debug params %>
<%= button_to "Send", send_path(link_id: @link.id, sender_id: current_user.id, username: @username), :method => :patch %>-->

app/views/links/send.html.erb
<h1>Send link</h1>

<%= simple_form_for @link, :method=>"patch" do |f| %>
  <%= f.input :user_name %>
  <%= f.button :submit, "Send" %>
<% end %>

app/views/users/index.html.erb
<div class = "row fluid">
	<div class = "span6 well">


	
<% if current_user %>	
	<%= current_user.name %>
	<%= button_to "Create a New Link!", new_user_link_path(user_id: current_user.id), :class => "btn btn-info", :method => :get %>

	<% @links = Link.all %>
	<br>
	<h2>Your links:</h2>
	<br>
	<% @links.each do |l| %>
	        <% if l.user_id == current_user.id %>
	        		Title: <%= l.title %>
	        		<br>
	                URL:  <%= l.url %>
	                <br>
	                Points: <%= l.points %>
	                <br>
	               <%= button_to "Send a Link!", pre_send_path(sender_id: current_user.id, link_id: l.id), :class => "btn btn-info", :method => :patch %>
	               <br>
	               <br>
	        <% end %>
	<% end %>
	<h2>Links Received:</h2>
	<% @user = current_user %>
	<% if @user.received %>
		<% @user.received.each do |link_id| %>
		<% @link = Link.find(link_id) %>
		<% @link.receivers.each do |arr| %>
			<% if arr[0]  == @user.id %>
				<% sender_id = arr[1] %>
				Title: <%= @link.title %> 
				<br>
				URL: <%= @link.url %>
				<br>
				Sender: <%= (User.find(sender_id)).name %>
				<br>
				Link creator: <%= User.find(@link.user_id).name %>
				<br>
				Points: <%= @link.points %>
				<br>
				<%= button_to "Send a Link!", pre_send_path(sender_id: current_user.id, link_id: @link.id), :class => "btn btn-info", :method => :patch %>
				<br>
				<br>
				<% break %>
			<% end %>
		<% end %> 
	<% end %>
<% end %>
	<h2>Your Friends are Waiting</h2>
	<%= button_to "View Friends!", friends_path, :class => "btn btn-info", :method => :get %>


<% else %>
	<h3>Welcome to Linq!</h3>
    <h4>Linq is a quick and fun way to share all sorts of media with your friends. You can share music, videos, articles, photos, and more! All you need is the link. Share links with friends, discard ones you don't like, and circulate ones you do to gather more points.</h4>
	</BR>
	<div align = "center">
		<%= link_to "Login", new_user_session_path %> or <%= link_to "Sign Up", new_user_registration_path %> to get started!
	</div>      
<% end %>
	</div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
<%= link_to t(".sign_in", :default => "Sign in"), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
<%= link_to t(".sign_up", :default => "Sign up"), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
<%= link_to t(".forgot_your_password", :default => "Forgot your password?"), new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
<%= link_to t('.didn_t_receive_confirmation_instructions', :default => "Didn't receive confirmation instructions?"), new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
<%= link_to t('.didn_t_receive_unlock_instructions', :default => "Didn't receive unlock instructions?"), new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
  <%= link_to t('.sign_in_with_provider', :provider => provider.to_s.titleize, :default => "Sign in with #{provider.to_s.titleize}"), omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1>User</h1>

<p>Name: <%= @user.name if @user.name %></p>
<% if @user.received %>
	<% @user.received.each do |link_id| %>
		<% @link = Link.find(link_id) %>
		<% @link.receivers.each do |arr| %>
			<% if arr[0]  == @user.id %>
				<% sender_id = arr[1] %>
				Title: <%= @link.title %> 
				<br>
				URL: <%= @link.url %>
				<br>
				Sender: <%= (User.find(sender_id)).name %>
				<br>
				Points: <%= @link.points %>
				<br>
				<% break %>
			<% end %>

		<% end %> 
	<% end %>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello There</h1>